name: Output Issue Expression
on:
  issues:
    types: [opened]
jobs:
  issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Expression
        run: echo "${{ toJSON(github) }}"
